spring:
  # Database
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:test;MODE=PostgreSQL"
    username: "tiger"
    password: "tiger"
    data: "classpath:data.sql"
    initialization-mode: always
  # JPA Properties
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: "H2"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
server:
  port: 8080