spring:
  # Database
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password:
    data: "classpath:data.sql"
    initialization-mode: always
  # JPA Properties
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: "H2"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"